weko_itemtypes_ui/__init__.py
# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

"""UI for creating item type and mapping information."""

from .ext import WekoItemtypesUI
from .version import __version__

__all__ = ('__version__', 'WekoItemtypesUI')

weko_itemtypes_ui/views.py
# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

"""Blueprint for weko-itemtypes-ui."""

from flask import abort, Blueprint, current_app, json, jsonify, redirect, \
    render_template, request, url_for, Flask, make_response
from flask_babelex import gettext as _
from flask_login import login_required, current_user
from invenio_db import db
from weko_records.api import ItemTypes, ItemTypeProps, Mapping

from .permissions import item_type_permission

blueprint = Blueprint(
    'weko_itemtypes_ui',
    __name__,
    url_prefix='/itemtypes',
    template_folder='templates',
    static_folder='static',
)


@blueprint.route("/", methods=['GET'])
@blueprint.route("/<int:item_type_id>", methods=['GET'])
@blueprint.route("/register", methods=['GET'])
@login_required
@item_type_permission.require(http_exception=403)
def index(item_type_id=0):
    """Renders an item type register view.

    :param item_type_id: Item type i. Default 0.
    """
    lists = ItemTypes.get_latest()
    return render_template(
        current_app.config['WEKO_ITEMTYPES_UI_REGISTER_TEMPLATE'],
        lists=lists,
        id=item_type_id
    )


@blueprint.route("/<int:item_type_id>/render", methods=['GET'])
@login_required
@item_type_permission.require(http_exception=403)
def render(item_type_id=0):
    result = None
    if item_type_id > 0:
        result = ItemTypes.get_by_id(id_=item_type_id)
    if result is None:
        result = {
            'table_row': [],
            'table_row_map': {},
            'meta_list': {},
            'schemaeditor': {
                'schema': {}
            }
        }
    return jsonify(result.render)


@blueprint.route("/register", methods=['POST'])
@blueprint.route("/<int:item_type_id>/register", methods=['POST'])
@login_required
@item_type_permission.require(http_exception=403)
def register(item_type_id=0):
    """Register an item type."""
    if request.headers['Content-Type'] != 'application/json':
        current_app.logger.debug(request.headers['Content-Type'])
        return jsonify(msg=_('Header Error'))

    data = request.get_json()
    try:
        record = ItemTypes.update(id_=item_type_id,
                                  name=data.get('table_row_map').get('name'),
                                  schema=data.get('table_row_map').get(
                                      'schema'),
                                  form=data.get('table_row_map').get('form'),
                                  render=data)
        Mapping.create(item_type_id=record.model.id,
                       mapping=data.get('table_row_map').get('mapping'))
        db.session.commit()
    except:
        db.session.rollback()
        return jsonify(msg=_('Fail'))
    current_app.logger.debug('itemtype register: {}'.format(item_type_id))
    return jsonify(msg=_('Success'))


@blueprint.route("/property", methods=['GET'])
@login_required
@item_type_permission.require(http_exception=403)
def custom_property(property_id=0):
    """Renders an primitive property view."""
    lists = ItemTypeProps.get_records([])
    return render_template(
        current_app.config['WEKO_ITEMTYPES_UI_CREATE_PROPERTY'],
        lists=lists
    )


@blueprint.route("/property/list", methods=['GET'])
@login_required
@item_type_permission.require(http_exception=403)
def get_property_list(property_id=0):
    """Renders an primitive property view."""
    props = ItemTypeProps.get_records([])
    lists = {}
    for k in props:
        tmp = {}
        tmp['name'] = k.name
        tmp['schema'] = k.schema
        tmp['form'] = k.form
        tmp['forms'] = k.forms
        lists[k.id] = tmp

    return jsonify(lists)


@blueprint.route("/property/<int:property_id>", methods=['GET'])
@login_required
@item_type_permission.require(http_exception=403)
def get_property(property_id=0):
    """Renders an primitive property view."""
    prop = ItemTypeProps.get_record(property_id)
    tmp = {}
    tmp['id'] = prop.id
    tmp['name'] = prop.name
    tmp['schema'] = prop.schema
    tmp['form'] = prop.form
    tmp['forms'] = prop.forms
    return jsonify(tmp)


@blueprint.route("/property", methods=['POST'])
@blueprint.route("/property/<int:property_id>", methods=['POST'])
@login_required
@item_type_permission.require(http_exception=403)
def custom_property_new(property_id=0):
    """Register an item type."""
    if request.headers['Content-Type'] != 'application/json':
        current_app.logger.debug(request.headers['Content-Type'])
        return jsonify(msg=_('Header Error'))

    data = request.get_json()
    try:
        ItemTypeProps.create(property_id=property_id,
                             name=data.get('name'),
                             schema=data.get('schema'),
                             form_single=data.get('form1'),
                             form_array=data.get('form2'))
        db.session.commit()
    except Exception as ex:
        current_app.logger.debug(ex)
        db.session.rollback()
        return jsonify(msg=_('Fail'))
    return jsonify(msg=_('Success'))


@blueprint.route("/mapping", methods=['GET'])
@blueprint.route("/mapping/<int:ItemTypeID>", methods=['GET'])
@login_required
@item_type_permission.require(http_exception=403)
def mapping_index(ItemTypeID=0):
    """Renders an item type mapping view.

    :param ItemTypeID: Item type ID. (Default: 0)
    :return: The rendered template.
    """
    lists = ItemTypes.get_all()
    if lists is None or len(lists) == 0:
        return render_template(
            current_app.config['WEKO_ITEMTYPES_UI_ERROR_TEMPLATE']
        )
    item_type = ItemTypes.get_by_id(ItemTypeID)
    if item_type is None:
        return redirect(url_for('.mapping_index', ItemTypeID=lists[0].id))
    item_type_mapping = Mapping.get_record(ItemTypeID)
    mapping = json.dumps(item_type_mapping, indent=4, ensure_ascii=False)
    current_app.logger.debug(mapping)
    return render_template(
        current_app.config['WEKO_ITEMTYPES_UI_MAPPING_TEMPLATE'],
        lists=lists,
        mapping=mapping,
        id=ItemTypeID
    )


@blueprint.route("/mapping", methods=['POST'])
@login_required
@item_type_permission.require(http_exception=403)
def mapping_register():
    """Register an item type mapping."""
    if request.headers['Content-Type'] != 'application/json':
        current_app.logger.debug(request.headers['Content-Type'])
        return jsonify(msg=_('Header Error'))

    data = request.get_json()
    current_app.logger.debug(data)
    try:
        Mapping.create(item_type_id=data.get('item_type_id'),
                       mapping=json.loads(data.get('mapping')))
        db.session.commit()
    except:
        db.session.rollback()
        return jsonify(msg=_('Fail'))
    return jsonify(msg=_('Success'))

weko_itemtypes_ui/templates/weko_itemtypes_ui/_macros.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{% macro render_field(field, icon="", autofocus=False, errormsg=True, size="form-group-lg", show_description=False) %}
  <div class="form-group {{size}}{% if icon %} has-feedback{% endif %}{% if field.errors %} has-error{% endif %}">
    {%- set extras = dict(autofocus="") if autofocus else dict() %}
    {{field(class_="form-control", placeholder=_(field.label.text), **extras)}}
    {%- if icon %}
    <i class="{{icon}} form-control-feedback" aria-hidden="true" ></i>
    {%- endif%}
  </div>
  {%- if field.errors and errormsg %}
  <div class="text-danger text-left" role="alert">
    {%- for error in field.errors %}
    <p>{{error}}</p>
    {%- endfor %}
  </div>
  {%- endif %}
  {% if show_description and field.description %}
  <div class="help-block"><small>{{ field.description }}</small></div>
  {% endif %}
{% endmacro %}

{% macro form_errors(form) %}
  {%- if form.errors %}
  <div class="alert alert-danger alert-dismissible text-left" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {%- for field, errors in form.errors.items() %}
    {%- for error in errors %}
      <p>{{error}}</p>
    {%- endfor %}
  {%- endfor %}
  </div>
  {%- endif %}
{% endmacro %}

weko_itemtypes_ui/templates/weko_itemtypes_ui/base.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {%- block css %}{%- endblock css %}
    {%- block javascript %}{%- endblock javascript %}
  </head>
  <body>
    <div>weko_itemtyps_ui base html</div>
    {%- block page_body %}{%- endblock page_body %}
  </body>
</html>

weko_itemtypes_ui/templates/weko_itemtypes_ui/create_property.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_ITEMTYPES_UI_BASE_TEMPLATE %}

{%- block css %}
{{ super() }}
{% assets "weko_itemtypes_ui_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{%- endblock css %}

{%- block javascript %}
  <script src="/static/node_modules/react/dist/react.js"></script>
  <script src="/static/node_modules/react-dom/dist/react-dom.js"></script>
  <script src="/static/js/weko_itemtypes_ui/jsonschemaeditor.js"></script>
  {{ super() }}
  {% assets "weko_itemtypes_property_ui_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/edit_tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('item type') }}
{%- endblock page_body_tabs%}

{%- block page_body_main %}
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-11">
      <div class="panel panel-info">
        <div class="panel-body">
          <div class="form-inline">
            <div class="input-group">
              <label class="sr-only" for="item-type-lists"></label>
              <select class="form-control" id="item-type-lists">
                <option  value=""></option>
                {% for list in lists %}
                <option  value="{{ list.id }}" {% if list.id == id %}selected{% endif %}>{{ list.name }}</option>
                {% endfor %}
              </select>
            </div>
            <a type="button" class="btn btn-default pull-right" href="{{ url_for('weko_itemtypes_ui.index') }}">{{ _('Item Types') }}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-11">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="form-inline">
            <div class="form-group">
              <label for="property_name">{{_('Property Name')}}</label>
              <input type="text" id="property_name" class="form-control" value="" />
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div id="new_option"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-11">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <button type="button" class="btn btn-default" id="previews">
                    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> {{_('Json Schema')}}
                  </button>
                  <button type="button" class="btn btn-default" id="rebuild"> {{_('Reset')}} </button>
                </div>
                <div class="panel-body">
                  <!--<pre class="pre-scrollable" id="schema_json"></pre>-->
                  <textarea class="form-control pre-scrollable" rows="50" id="schema_json"></textarea>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">{{_('Form(Singular)')}}</h3>
                </div>
                <div class="panel-body">
                  <textarea class="form-control pre-scrollable" rows="50" id="form1_json"></textarea>
                </div>
              </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">{{_('Form(Multiple)')}}</h3>
                </div>
                <div class="panel-body">
                  <textarea class="form-control pre-scrollable" rows="50" id="form2_json"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <button class="btn btn-default" id="sending">{{_('Sending')}}</button>
        </div>
      </div>
    </div>
  </div>
{%- endblock page_body_main%}
{%- block page_body%}
{{ super() }}
<!-- modal start -->
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{_('Result')}}</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{_('Close')}}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{%- endblock page_body%}

weko_itemtypes_ui/templates/weko_itemtypes_ui/error.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_ITEMTYPES_UI_BASE_TEMPLATE %}

{%- block css %}
  {{ super() }}
{%- endblock css %}

{%- block page_body %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-10">
      <div class="panel panel-warning">
        <div class="panel-body">
          {{_('You do not even have an itemtype.')}}<br>
          {{_('Go to')}} <a href="{{ url_for('weko_itemtypes_ui.index') }}">{{_('Register Itemtype')}}</a>!
        </div>
      </div>
    </div>
  </div>
</div>
{%- endblock page_body%}

weko_itemtypes_ui/templates/weko_itemtypes_ui/mapping.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_ITEMTYPES_UI_BASE_TEMPLATE %}

{%- block css %}
  {{ super() }}
{%- endblock css %}

{%- block javascript %}
  {{ super() }}
  {% assets "weko_itemtypes_mapping_ui_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/edit_tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('item type') }}
{%- endblock page_body_tabs%}

{%- block page_body_main %}
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-10">
      <div class="panel panel-info">
        <div class="panel-body">
          <div class="form-inline">
            <div class="form-group">
              <label for="item-type-lists">{{_('itemtype list')}}</label>
              <select class="form-control" id="item-type-lists">
                {% for list in lists %}
                <option  value="{{ list.id }}" {% if list.id == id %}selected{% endif %}>{{ list.item_type_name.name }}({{ list.tag }})</option>
                {% endfor %}
              </select>
            </div>
            <a type="button" class="btn btn-default pull-right" href="{{ url_for('weko_itemtypes_ui.index') }}">{{ _('Item Types') }}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-10">
      <div class="form-horizontal">
        <div class="form-group">
          <label for="itemtype-schema-mapping" class="col-sm-2 control-label">SchemaMapping</label>
          <div class="col-sm-10">
            <textarea class="form-control" rows="30" id="itemtype-schema-mapping">{{ mapping }}</textarea>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-12 col-md-12 col-lg-10">
            <button id="mapping-submit" class="btn btn-default">{{_('sending')}}</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{%- endblock page_body_main%}
{%- block page_body%}
{{ super() }}
<!-- modal start -->
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{_('Result')}}</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{_('Close')}}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{%- endblock page_body %}